Add windowsHide to exec
node-opcua/node-opcua-pki pull request #23
Opened 2021-08-24 18:54 UTC by BartaG512

https://github.com/node-opcua/node-opcua-pki/issues/22

2021-08-24 18:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-opcua/node-opcua-pki?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/node-opcua/node-opcua-pki?pullRequest=23) before we can accept your contribution.<br/><hr/>**barta.gergo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-opcua/node-opcua-pki?pullRequest=23) it.</sub>

2021-08-30 10:41 UTC, BartaG512 commented
@erossignon Can you check if this pull request is ok? Or what else we need to do to accept?

2021-09-05 06:21 UTC, erossignon requested changes

2021-09-05 06:21 UTC, erossignon commented on lib/pki/toolbox.ts
> +    }
``` javascript
const execOptions: any = {
        cwd: options.cwd,
    };

    if (process.platform === "win32") {
        execOptions.windowsHide = true;
    }
    const child = child_process.exec(
        cmd,
        {
            cwd: options.cwd,
        },
````

could be simpler this way :
```javascript
const child = child_process.exec(
        cmd,
        {
            cwd: options.cwd,
            windowsHide:  true
        },
```

2021-09-05 06:21 UTC, erossignon commented on lib/misc/install_prerequisite.ts
> +
I guess that windowsHide can true in al circunstancies

```javascript
 const options: any = {};
    if (cwd) {
        options.cwd = cwd;
    }

    if (process.platform === "win32") {
        options.windowsHide = true;
    }
```
could be simplified as:

```javascript
const options = {
   cwd,
   windowsHide:  true
};
````

2021-09-05 21:18 UTC, merged