LibreSSL Support
node-opcua/node-opcua-pki pull request #5
Opened 2018-01-19 08:49 UTC by bompi88

Generate static config files to support LibreSSL (issue #4 ). Also do not provide random generator files if LibreSSL is detected, as it's not a viable CLI option. @erossignon If there's something you want me to change, let me know.

2018-01-19 10:46 UTC, erossignon commented
Thank you @bompi88  , would it be possible to adapt the travis script so we run tests on MacOS ?
That would be awesome.

2018-01-19 10:50 UTC, erossignon requested changes

2018-01-19 10:50 UTC, erossignon commented on lib/pki/certificate_authority.js
>          toolbox.setEnv("OPENSSL_CONF", toolbox.make_path(self.configFile));
Could we avoid code duplication ?

2018-01-19 10:50 UTC, erossignon commented on lib/pki/toolbox.js
> +    return Object.keys(process.env).map(function(varName) { return { key: varName, pattern: '\\$ENV\\:\\:' + varName }; });
Would be good to export only env variable that are set by us , not the one that exists on the system .
( this could create a backdoor)

2018-01-22 13:48 UTC, bompi88 commented on lib/pki/certificate_authority.js
> +    var configFile = toolbox.generateStaticConfig("conf/caconfig.cnf", { cwd: self.rootDir });
@erossignon Should `conf/caconfig.cnf` be `self.configFile`?

2018-01-22 13:50 UTC, bompi88 commented on lib/pki/toolbox.js
> +    if (["OPENSSL_CONF"].indexOf(varName) >= 0) {
@erossignon I assume `OPENSSL_CONF` is needed in systems` environment vars?

2018-01-22 13:57 UTC, bompi88 commented
@erossignon I see I triggered a lot of builds in travis, which seems to stall, feel free to cancel all except the last one

2018-01-23 07:40 UTC, merged